/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package speechrecognition;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import org.encog.neural.networks.BasicNetwork;
import org.encog.neural.networks.PersistBasicNetwork;
import org.encog.persist.EncogDirectoryPersistence;
import speechrecognition.audio.Clip;
import speechrecognition.audio.ClipCapture;
import speechrecognition.audio.ClipPlayback;
import speechrecognition.audio.features.FeaturesExtractor;
import speechrecognition.audio.features.PerFrameBandsFeatureExtractor;
import speechrecognition.audio.features.PerFrameStrongFreqsFeatureExtractor;
import speechrecognition.audio.features.SpectrumFeatureExtractor;
import speechrecognition.util.ArrayUtil;

/**
 *
 * @author davinchi
 */
public class Recognize extends javax.swing.JFrame {

    private final int NUMBERS_COUNT = 10;
    private JFileChooser fc = new JFileChooser();
    private FeaturesExtractor fe = null;
    private List<String> dictorsList = null;
    private BasicNetwork neuralNetwork = null;
    private ClipCapture clipCapture = null;
    private ClipPlayback clipPlayback = null;
    private Clip clip = null;

    /**
     * Creates new form Recognize
     */
    public Recognize() {
        initComponents();

        readDefaultFiles();
    }

    private void readDefaultFiles() {
        File file = new File("serialized.txt");
        if (file.exists()) {
            readSoundbase(file);
        }

        file = new File("nn.eg");
        if (file.exists()) {
            readNeuralNetwork(file);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jReadSoundbaseButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDictorsLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFELabel = new javax.swing.JLabel();
        jReadNetworkButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jNNLabel = new javax.swing.JLabel();
        jRecordButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRecognizeResults = new javax.swing.JTextArea();
        jPlayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jReadSoundbaseButton.setText("Read Soundbase");
        jReadSoundbaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReadSoundbaseButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Dictors:");

        jDictorsLabel.setText("0");

        jLabel2.setText("Features Extractor:");

        jFELabel.setText(null);

        jReadNetworkButton.setText("Read network");
        jReadNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReadNetworkButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("NN info:");

        jNNLabel.setText(null);

        jRecordButton.setText("Record");
        jRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecordButtonActionPerformed(evt);
            }
        });

        jRecognizeResults.setColumns(20);
        jRecognizeResults.setRows(5);
        jRecognizeResults.setText("Recognition here");
        jScrollPane1.setViewportView(jRecognizeResults);

        jPlayButton.setText("Play");
        jPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jReadSoundbaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jReadNetworkButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRecordButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNNLabel)
                            .addComponent(jDictorsLabel)
                            .addComponent(jFELabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReadSoundbaseButton)
                    .addComponent(jLabel1)
                    .addComponent(jDictorsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFELabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReadNetworkButton)
                    .addComponent(jLabel4)
                    .addComponent(jNNLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRecordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPlayButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseNeuralNetwork() {
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int returnVal = fc.showOpenDialog(Recognize.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            readNeuralNetwork(file);
        }

    }

    private void readNeuralNetwork(File file) {
        neuralNetwork = (BasicNetwork) EncogDirectoryPersistence.loadObject(file);

        StringBuilder nnlabel = new StringBuilder();

        nnlabel.append("Layers: ");
        nnlabel.append(String.valueOf(neuralNetwork.getLayerCount()));
        nnlabel.append("; ");

        nnlabel.append("Total neurons: ");
        for (int i = 0; i < neuralNetwork.getLayerCount(); ++i) {
            nnlabel.append(String.valueOf(neuralNetwork.getLayerTotalNeuronCount(i)));
            if (i != neuralNetwork.getLayerCount() - 1) {
                nnlabel.append(", ");
            }
        }

        jNNLabel.setText(nnlabel.toString());
    }

    private void chooseSoundbase() {
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int returnVal = fc.showOpenDialog(Recognize.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            readSoundbase(file);
        }
    }

    private void readSoundbase(File file) {
        /* TODO: write class with this info */
        try {
            final FileInputStream fis = new FileInputStream(file);
            final BufferedReader br = new BufferedReader(new InputStreamReader(fis));

            String version = br.readLine();
            //System.out.println(version);

            int dictorsCount = Integer.parseInt(br.readLine());
            StringBuilder dictorsTotal = new StringBuilder();
            dictorsTotal.append(String.valueOf(dictorsCount));
            dictorsTotal.append(": ");
            dictorsList = new ArrayList<String>();

            for (int i = 0; i < dictorsCount; ++i) {
                String dictorName = br.readLine();
                dictorsList.add(dictorName);
                dictorsTotal.append(dictorName);
                if (i != dictorsCount - 1) {
                    dictorsTotal.append(",");
                }
            }

            jDictorsLabel.setText(dictorsTotal.toString());


            System.out.println(br.readLine());
            String feName = br.readLine();
            jFELabel.setText(feName);

            if (feName.equals("PerFrameBandsFeatureExtractor")) {
                fe = PerFrameBandsFeatureExtractor.fromStream(br);
            } else if (feName.equals("SpectrumFeatureExtractor")) {
                fe = SpectrumFeatureExtractor.fromStream(br);
            } else if (feName.equals("PerFrameStrongFreqsFeatureExtractor")) {
                fe = PerFrameStrongFreqsFeatureExtractor.fromStream(br);
            }

        } catch (IOException e) {
            jRecognizeResults.append(e.getMessage() + "\n");
        }
    }

    private void startPlayback() {
        clipPlayback = new ClipPlayback(clip.getAudioInputStream());
        clipPlayback.start();
        jPlayButton.setText("Stop");
    }

    private void stopPlayback() {
        clipPlayback.stop();
        jPlayButton.setText("Play");
    }

    private void startRecording() {
        if (fe == null) {
            return;
        }

        clipCapture = new ClipCapture();

        clipCapture.start();
        jRecordButton.setText("Stop");
    }

    private void stopRecording() {

        if (fe == null) {
            return;
        }

        jRecordButton.setText("Record");
        try {
            clipCapture.stop();
        } catch (Exception e) {
            jRecognizeResults.append(e.getMessage());
            return;
        }


        try {
            clip = Clip.newInstance(clipCapture.getAudioInputStream());
        } catch (Exception e) {
            jRecognizeResults.append(e.getMessage());
            return;
        } finally {
            clipCapture = null;
        }

        fe.featureFromClip(clip);
        double[] fv = fe.extractFeatureVector(clip);
        double[] output = new double[dictorsList.size() * NUMBERS_COUNT];
        neuralNetwork.compute(fv, output);


        jRecognizeResults.append("\nFV: ");
        jRecognizeResults.append(Arrays.toString(fv) + "\n");

        /*
         jRecognizeResults.append("Output: ");
         jRecognizeResults.append(Arrays.toString(output) + "\n");
         */

        int[] idx = ArrayUtil.argsort(output, false);
        jRecognizeResults.append(Arrays.toString(idx) + "\n");
        int strongest = idx[0];

        jRecognizeResults.append(
                "Dictor: " + String.valueOf(dictorsList.get(strongest / NUMBERS_COUNT))
                + ", Number: " + String.valueOf(strongest % NUMBERS_COUNT)
                + ", Value: " + String.valueOf(output[strongest])
                + "\n");
    }

    private void jReadSoundbaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReadSoundbaseButtonActionPerformed
        // TODO add your handling code here:
        chooseSoundbase();
    }//GEN-LAST:event_jReadSoundbaseButtonActionPerformed

    private void jReadNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReadNetworkButtonActionPerformed
        // TODO add your handling code here:
        chooseNeuralNetwork();
    }//GEN-LAST:event_jReadNetworkButtonActionPerformed

    private void jRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecordButtonActionPerformed
        // TODO add your handling code here:
        if (clipCapture == null) {
            startRecording();
        } else {
            stopRecording();
        }
    }//GEN-LAST:event_jRecordButtonActionPerformed

    private void jPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayButtonActionPerformed
        // TODO add your handling code here:
        if (clipCapture == null) {
            startPlayback();
        } else {
            stopPlayback();
        }
    }//GEN-LAST:event_jPlayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recognize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recognize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recognize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recognize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recognize().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDictorsLabel;
    private javax.swing.JLabel jFELabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jNNLabel;
    private javax.swing.JButton jPlayButton;
    private javax.swing.JButton jReadNetworkButton;
    private javax.swing.JButton jReadSoundbaseButton;
    private javax.swing.JTextArea jRecognizeResults;
    private javax.swing.JButton jRecordButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
